version: '3'

services:

  php:
    container_name: php
    build: ./docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - 85:80
    links:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  rabbitmq:
    image: rabbitmq:3.7.7
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "15672:15672"
