version: '3'

services:

  php:
    container_name: php
    build: ./docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - 85:80
    links:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: cuterabbit
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "root"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
